[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DSPCoder"
authors = [{name = "Ninad Kale", email = "ninadkale98@gmail.com"}]
dynamic = ["version", "description"]
